/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mysimpleapp;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPA = new javax.swing.JTextField();
        lbPlus = new javax.swing.JLabel();
        txtPB = new javax.swing.JTextField();
        lbEqualPlus = new javax.swing.JLabel();
        txtPC = new javax.swing.JTextField();
        bnPlus = new javax.swing.JButton();
        txtMA = new javax.swing.JTextField();
        lbMinus = new javax.swing.JLabel();
        txtMB = new javax.swing.JTextField();
        lbEqualMinus = new javax.swing.JLabel();
        txtMC = new javax.swing.JTextField();
        bnMinus = new javax.swing.JButton();
        txtMulA = new javax.swing.JTextField();
        lbMul = new javax.swing.JLabel();
        txtMulB = new javax.swing.JTextField();
        lbEqual2 = new javax.swing.JLabel();
        txtMulC = new javax.swing.JTextField();
        bnMultiply = new javax.swing.JButton();
        txtDivA = new javax.swing.JTextField();
        lbDivision = new javax.swing.JLabel();
        txtDivB = new javax.swing.JTextField();
        lbEqual3 = new javax.swing.JLabel();
        txtDivC = new javax.swing.JTextField();
        bnDiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hello World");

        lbPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlus.setText("+");
        lbPlus.setToolTipText("");

        lbEqualPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEqualPlus.setText("=");

        bnPlus.setText("+");
        bnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnPlusActionPerformed(evt);
            }
        });

        lbMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMinus.setText("-");
        lbMinus.setToolTipText("");

        lbEqualMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEqualMinus.setText("=");

        bnMinus.setText("-");
        bnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnMinusActionPerformed(evt);
            }
        });

        lbMul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMul.setText("*");
        lbMul.setToolTipText("");

        lbEqual2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEqual2.setText("=");

        bnMultiply.setText("*");
        bnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnMultiplyActionPerformed(evt);
            }
        });

        lbDivision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDivision.setText("/");
        lbDivision.setToolTipText("");

        lbEqual3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEqual3.setText("=");

        bnDiv.setText("/");
        bnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEqualPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDivA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDivB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEqual3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDivC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEqualMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMulA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMul, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMulB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEqual2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMulC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlus)
                    .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEqualPlus)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMinus)
                    .addComponent(txtMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEqualMinus)
                    .addComponent(txtMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnMinus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMulA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMul)
                    .addComponent(txtMulB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEqual2)
                    .addComponent(txtMulC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnMultiply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDivA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDivision)
                    .addComponent(txtDivB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEqual3)
                    .addComponent(txtDivC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnDiv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnPlusActionPerformed
        // TODO add your handling code here:
        
        String a = txtPA.getText();
        String b = txtPB.getText();
        
        //เป็นการ เปลี่ยนจาก string ให้เป็น int ผ่านการใช้
        //class Integer
        int intA = new Integer(a);
        int intB = new Integer(b);
        int intC = intA+intB;
        
        String c = Integer.toString(intC);
        //เป็นการเซ็ตค่า Text ให้กับ txtC [JTextField] 
        txtPC.setText(c); 
        
    }//GEN-LAST:event_bnPlusActionPerformed

    private void bnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnMinusActionPerformed
        int a = Integer.parseInt(txtMA.getText());
        int b = Integer.parseInt(txtMB.getText());
        int c = a-b;
        txtMC.setText(Integer.toString(c));
    }//GEN-LAST:event_bnMinusActionPerformed

    private void bnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnMultiplyActionPerformed
        int a = Integer.parseInt(txtMulA.getText());
        int b = Integer.parseInt(txtMulB.getText());
        int c = a*b;
        txtMulC.setText(Integer.toString(c));
    }//GEN-LAST:event_bnMultiplyActionPerformed

    private void bnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDivActionPerformed
        int a = Integer.parseInt(txtDivA.getText());
        int b = Integer.parseInt(txtDivB.getText());
        int c = a/b;
        txtDivC.setText(Integer.toString(c));
    }//GEN-LAST:event_bnDivActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnDiv;
    private javax.swing.JButton bnMinus;
    private javax.swing.JButton bnMultiply;
    private javax.swing.JButton bnPlus;
    private javax.swing.JLabel lbDivision;
    private javax.swing.JLabel lbEqual2;
    private javax.swing.JLabel lbEqual3;
    private javax.swing.JLabel lbEqualMinus;
    private javax.swing.JLabel lbEqualPlus;
    private javax.swing.JLabel lbMinus;
    private javax.swing.JLabel lbMul;
    private javax.swing.JLabel lbPlus;
    private javax.swing.JTextField txtDivA;
    private javax.swing.JTextField txtDivB;
    private javax.swing.JTextField txtDivC;
    private javax.swing.JTextField txtMA;
    private javax.swing.JTextField txtMB;
    private javax.swing.JTextField txtMC;
    private javax.swing.JTextField txtMulA;
    private javax.swing.JTextField txtMulB;
    private javax.swing.JTextField txtMulC;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPB;
    private javax.swing.JTextField txtPC;
    // End of variables declaration//GEN-END:variables



}
